### ISSUE TITLE
can not install hyperinator and hyperpwn

### ISSUE THREAD

**Issue by soez** [bet4it/hyperpwn#1]
Hi, I get the following error when typing hyper i hyperinator and hyper i hyperpwn

> noname@ubuntu:~$ hyper i hyperinator
> /opt/Hyper/resources/bin/cli.js:19156
>       getProperties = memoize(() => getParsedFile().program.body[0].expression.right.properties),
>                                                                                     ^
> 
> TypeError: Cannot read property 'properties' of undefined
>     at memoize (/opt/Hyper/resources/bin/cli.js:19156:85)
>     at d (/opt/Hyper/resources/bin/cli.js:19141:22)
>     at memoize (/opt/Hyper/resources/bin/cli.js:19157:34)
>     at d (/opt/Hyper/resources/bin/cli.js:19141:22)
>     at Object.install (/opt/Hyper/resources/bin/cli.js:19187:37)
>     at Args.args.command (/opt/Hyper/resources/bin/cli.js:9934:45)
>     at Args.runCommand (/opt/Hyper/resources/bin/cli.js:11318:37)
>     at Args.module.exports [as parse] (/opt/Hyper/resources/bin/cli.js:15089:10)
>     at main (/opt/Hyper/resources/bin/cli.js:9991:18)
>     at Object.module.exports.name (/opt/Hyper/resources/bin/cli.js:10038:1)
>
>
> noname@ubuntu:~$ hyper i hyperpwn
> /opt/Hyper/resources/bin/cli.js:19156
>       getProperties = memoize(() => getParsedFile().program.body[0].expression.right.properties),
>                                                                                     ^
> 
> TypeError: Cannot read property 'properties' of undefined
>     at memoize (/opt/Hyper/resources/bin/cli.js:19156:85)
>     at d (/opt/Hyper/resources/bin/cli.js:19141:22)
>     at memoize (/opt/Hyper/resources/bin/cli.js:19157:34)
>     at d (/opt/Hyper/resources/bin/cli.js:19141:22)
>     at Object.install (/opt/Hyper/resources/bin/cli.js:19187:37)
>     at Args.args.command (/opt/Hyper/resources/bin/cli.js:9934:45)
>     at Args.runCommand (/opt/Hyper/resources/bin/cli.js:11318:37)
>     at Args.module.exports [as parse] (/opt/Hyper/resources/bin/cli.js:15089:10)
>     at main (/opt/Hyper/resources/bin/cli.js:9991:18)
>     at Object.module.exports.name (/opt/Hyper/resources/bin/cli.js:10038:1)

regards

**Comment by bet4it** [comment]
This is a bug of hyper, more details in zeit/hyper#3500
