### ISSUE TITLE
How can I use hyperpwn with rr-debugger

### ISSUE THREAD

**Issue by bulletforkiller** [bet4it/hyperpwn#12]
Layout is wrong when I run "rr replay" in hyper, I only see command and stack window.
And I use gef.

**Comment by bet4it** [comment]
Is the output of gef correct if you don't use gdb in hyper?
Could you post a screenshot of the wrong layout? Do you try `stepi` after the layout is loaded?

**Comment by bulletforkiller** [comment]
Without hyper:

![Peek 2021-12-19 01-43](https://user-images.githubusercontent.com/25951144/146650852-f110dc6a-e1d3-4989-af7e-c626eb6add42.gif)

In hyper:

![Peek 2021-12-19 01-41](https://user-images.githubusercontent.com/25951144/146650924-b5b9fb4c-7e3c-4dfc-8993-3f45d3c1f780.gif)

**Comment by bet4it** [comment]
Could you try to run `hyperinator load hyperpwn-gef` before `rr replay` likes this:
![](https://user-images.githubusercontent.com/16643669/61991962-5df7b100-b08a-11e9-9b9e-e811da4b8d11.gif)
(You may need to `npm install -g hyperinator` firstly)

And what's the version of hyper and gef do you use?

**Comment by bet4it** [comment]
Great! I have no idea why it can't be used directly, but at least we have a way to solve it 😃
