### ISSUE TITLE
hyperpwn doesn't work on OSX

### ISSUE THREAD

**Issue by sawflare** [bet4it/hyperpwn#3]
i already installed Hyper, and both plugins placed correctly, but when i typo gdb to start, it doesn't show any layout like GIF in the README. I play with GEF.and the ~/.hyperinator/ dir does not exist. the devtools output:
 Plugin hyperinator (0.3.4) loaded. bundle.js:1
 Plugin hyperpwn (0.2.2) loaded.   bundle.js:1
what should i do?

**Comment by bet4it** [comment]
Try `echo 'GEF for linux ready'` in Hyper?
Hyperpwn will detect the output of `GEF` and start automatically.

**Comment by 500646** [comment]
yes, this is the problem.because I'm on OSX.Thanks!

**Comment by bet4it** [comment]
Can `GEF` work on OSX?
I don't have a Mac to do testing, but I think the technology this plugin use is universal and should also work on OSX.

Can you also install `hyperinator` globally by `npm install -g hyperinator` and test it with ways listed [here](https://github.com/bet4it/hyperinator#usage)?

**Comment by 500646** [comment]
I test it with global, and hyperinator is work correct.may be I should install hyperpwn with global?

**Comment by bet4it** [comment]
Then what about copying [hyperpwn-gef.yml](https://github.com/bet4it/hyperpwn/blob/master/cfgs/hyperpwn-gef.yml) to `~/.hyperinator/hyperpwn-gef.yml` and run `hyperinator load hyperpwn-gef` likes this:
![](https://user-images.githubusercontent.com/16643669/61991962-5df7b100-b08a-11e9-9b9e-e811da4b8d11.gif)

**Comment by bet4it** [comment]
Can you run `/bin/sleep infinity` on OSX?

**Comment by 500646** [comment]
when I copyed the [hyperpwn-gef.yml](https://github.com/bet4it/hyperpwn/blob/master/cfgs/hyperpwn-gef.yml) to ~/.hyperinator/hyperpwn-gef.yml,the result is always like above i posted,say "hyperpwn: command not found".and I think the command `/bin/sleep infinity`
dosen't work on OSX. As [yvanscher said](https://unix.stackexchange.com/questions/42901/how-to-do-nothing-forever-in-an-elegant-way). last I test with install hyperpwn in global,and it still don't work like before.

**Comment by bet4it** [comment]
`hyperpwn` is a fake command and you can't install it. It only works when `sleep` is running correctly.

I think you should change `/bin/sleep` and `infinity` in `hyperpwn-gef.yml` to a sleep command which can run correctly, such as `/bin/sleep 99999`, and have a look of the result.

**Comment by FishMan132** [comment]
/bin/sleep 99999 
it's work

**Comment by bet4it** [comment]
> /bin/sleep 99999
> it's work

Hyperpwn works correctly on macOS? Can you post a screenshot about it?

**Comment by 500646** [comment]
> > /bin/sleep 99999
> > it's work
> 
> Hyperpwn works correctly on macOS? Can you post a screenshot about it?
![image](https://user-images.githubusercontent.com/10594524/72526033-72ca3a00-38a0-11ea-961e-90a2f736f81c.png)

yes,after use '99999' in hyperpwn-gef.yml it just work! and the xxx i test is remote debug with android gdbserver.btw:GEF seems doesn't support Mach-O format.

**Comment by FishMan132** [comment]
![image](https://user-images.githubusercontent.com/16998631/72673922-9d3c1300-3aab-11ea-9d0e-9fa889ca0931.png)
