### ISSUE TITLE
this plugin can not be installed by hyper

### ISSUE THREAD

**Issue by joeycold** [bet4it/hyperpwn#4]
when either fresh install or update plugin, hyper always pop notification,
![image](https://user-images.githubusercontent.com/10594524/76376545-7ef3e480-6383-11ea-9608-060e3c7edf12.png).
the install or update will be failed.the other hyper plugins work fine.

**Comment by bet4it** [comment]
I guess that's because `raw.githubusercontent.com` is blocked. Can you visit this [url](https://raw.githubusercontent.com/bet4it/expandtabs/master/package.json)?
You could try to install it under proxy. Or you can install this plugin locally by adding it to `localPlugins` in `.hyper.js`.

**Comment by syheliel** [comment]
Alternatively, you can use npm to directly install this plugin
```
cd ~/.hyper_plugins
npm install hyperpwn
```
